# Generated by Django 3.0.4 on 2020-06-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
