# Generated by Django 3.0.4 on 2020-06-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200626_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='image',
            new_name='background_image',
        ),
    ]
