# Generated by Django 3.0.4 on 2020-06-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200626_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='background_image',
            new_name='preview_image',
        ),
    ]
