# Generated by Django 3.0.4 on 2020-06-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0005_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_img', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_img', to='wagtailimages.Image'),
        ),
    ]
