# Generated by Django 3.0.4 on 2020-06-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0006_auto_20200622_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='background_img',
        ),
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_image', to='wagtailimages.Image'),
        ),
    ]
