# Generated by Django 3.0.4 on 2020-06-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
