# Generated by Django 3.0.4 on 2020-06-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20200618_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
    ]
