# Generated by Django 3.0.4 on 2020-06-27 18:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20200625_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, icon='title', null=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True, icon='pilcrow', null=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True, icon='media', null=True)), ('embed_HTML', wagtail.core.blocks.RawHTMLBlock(blank=True, help_text='use this to embed elements that do not embed using the normal embed block, e.g. google forms', null=True, required=False))], blank=True, null=True),
        ),
    ]
