# Generated by Django 3.0.4 on 2020-06-28 15:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_auto_20200627_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(blank=True, icon='title', null=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(blank=True, icon='pilcrow', null=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(blank=True, icon='media', null=True)), ('embed_HTML', wagtail.core.blocks.RawHTMLBlock(blank=True, help_text='use this to embed elements that do not embed using the normal embed block, e.g. google forms', null=True, required=False)), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='', required=False))])))]))], blank=True, null=True),
        ),
    ]
